version: '3.2'

services:
    squid:
        build: ./squid
        restart: always
        volumes:
          - ./squid/entrypoint.sh:/entrypoint.sh
          - ./squid/squid.conf:/etc/squid/squid.conf
        ports:
            - 3128:3128
        cap_add:
            - NET_ADMIN

    vpn:
        build: ./vpn
        restart: always
        volumes:
            - ./vpn/client.ovpn:/client.ovpn
            - ./vpn/routing.sh:/routing.sh
            - /dev/net:/dev/net
        command: ["openvpn", "--config", "/client.ovpn", "--script-security", "2", "--up", "/routing.sh"]
        cap_add:
            - NET_ADMIN
